// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDorJQv8LIKv5VB065RZnMSNzUgs67kFLA',
    appId: '1:8965936603:web:07e021fe539755847543fe',
    messagingSenderId: '8965936603',
    projectId: 'travelbott-38492',
    authDomain: 'travelbott-38492.firebaseapp.com',
    storageBucket: 'travelbott-38492.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsgErBB-W6oiXanhUC9GPbqXE8Lx779n8',
    appId: '1:8965936603:android:f576a60abbf0136d7543fe',
    messagingSenderId: '8965936603',
    projectId: 'travelbott-38492',
    storageBucket: 'travelbott-38492.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbkAVgSZAGBN6T6KKNAZajm_rKIJTTttc',
    appId: '1:8965936603:ios:0f5e0c66456d5c717543fe',
    messagingSenderId: '8965936603',
    projectId: 'travelbott-38492',
    storageBucket: 'travelbott-38492.firebasestorage.app',
    iosBundleId: 'com.example.travelBott',
  );
}
